scenario: configs/mt/mt_multi_turn_please_translate_again.yaml
prompts_path: data/processed/wmttest2024_plus_doc/en-de.jsonl
prompt_key: source
extra_data_fields:
  - source
  - target
  - lp
  - domain
  - document_id
  - segment_id
