model: Qwen/Qwen3-32B
ngpus: 4
vllm_runtime_config: configs/vllm_config/local_python.yaml
vllm_server_args:
  - "--max-model-len"
  - "32768"
  - "--gpu-memory-utilization"
  - "0.95"
  - "--max-num-batched-tokens"
  - "65536"
  - "--disable-uvicorn-access-log"
  - "--generation-config"
  - "vllm"
  - "--reasoning-parser"
  - "deepseek_r1"
scenario_override:
  temperature: 0.6
  top_k: 20
  top_p: 0.95
  max_tokens: 8196
  vllm_extra_body:
    chat_template_kwargs:
      enable_thinking: true
